version: "2"

services:
    gitea:
        container_name: gitea
        image: gitea/gitea:1.20.1-rootless
        restart: always
        volumes:
            - ./data:/var/lib/gitea
            - ./config:/etc/gitea
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3333:3000"
            - "2222:2222"
        networks:
            - backend
  
    backup:
        profiles: ['backup']
        image: alpine    
        tty: false
        user: 1000:1000
        environment:
            - TARGET=gitea
        volumes:
            - ../../backups:/backup
            - ./:/volume
        command: sh -c "tar -cvf /backup/$${TARGET}.tar -C /volume/*"

networks:
    backend:
        external: true
